version: "3.6"
### docker-compose -f docker-compose-mq.yaml up --detach
services:
  ibmmq1:
    image:              ibmcom/mq:9.1.1.0
    container_name:     ibmmq1
    hostname:           ibmmq1
    ports:
      - 1414:1414
      - 9443:9443
      - 9157:9157
    environment:
      - LICENSE=accept
      - MQ_QMGR_NAME=IBMQM1
      - MQ_ENABLE_METRICS=true
      - MQ_ADMIN_PASSWORD=passw0rd
      - MQ_APP_PASSWORD=passw0rd
      - LOG_FORMAT=basic
    volumes:
      - $GOPATH/src/github.com/gus-maurizio/:/sreagent
      - mqdata1:/mnt/mqm
#
volumes:
    mqdata1:
      driver: local
#