#
# docker build -f Dockerfile-build-mqgosdk -t gmaurizio/mqgosdk .
FROM ubuntu:18.04
ARG MQ_URL=http://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/messaging/mqadv/mqadv_dev911_ubuntu_x86-64.tar.gz
ARG MQ_PACKAGES="ibmmq-sdk ibmmq-client"
ARG LC_ALL=C
ARG GO_PACKAGE=https://dl.google.com/go/go1.11.linux-amd64.tar.gz
ARG GOROOT=/usr/local/go
ARG GOPATH=$HOME/go
ARG PATH=$GOPATH/bin:/usr/local/go/bin:$PATH

RUN apt-get update -y && \
    apt-get -y upgrade && \
    export LC_ALL=C && \
    apt-get install -y software-properties-common curl apt-utils wget git

RUN mkdir /root/go && cd /tmp && \
    wget --no-check-certificate ${GO_PACKAGE} && \
    tar -xvf go1*tar.gz && \
    mv go /usr/local


RUN apt-get update  -y  && \
    apt-get install -y  make automake gcc build-essential telnet vim less python3 python3-dev \
                        xinetd multipath-tools net-tools iputils-ping traceroute \
                        iftop iperf3 bmon nload pv python3-pip

COPY install-mqdev.sh /usr/local/bin/

# Install MQ.  To avoid a "text file busy" error here, we sleep before installing.
RUN chmod u+x /usr/local/bin/install-mqdev.sh \
  && sleep 1 \
  && echo "export LC_ALL=C" >>/etc/profile

RUN install-mqdev.sh

ENTRYPOINT ["/bin/bash"]
